---
version: "3.9"
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    tty: true
    volumes:
      - "/dev/shm:/dev/shm"
    environment:
      - "SE_VNC_NO_PASSWORD=1"

  server:
    image: node
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/../jest-selenium:/jest-selenium"
    working_dir: '/jest-selenium'
    entrypoint: 'yarn dev'

  tests:
    image: node
    tty: true
    volumes:
      - "$PWD/../jest-selenium:/jest-selenium"
    working_dir: '/jest-selenium'
    entrypoint: 'bash'  # 'yarn test'
    environment:
      - "DEV_URL=http://server:3000"
      - "SELENIUM_REMOTE_URL=http://chrome2:4444/wd/hub"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
