---
version: "3.9"
services:
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    tty: true
    volumes:
      - "/dev/shm:/dev/shm"
    environment:
      - "SE_VNC_NO_PASSWORD=1"

  server:
    image: node
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "$PWD:/project"
    working_dir: '/project'
    entrypoint: 'yarn dev'

  tests:
    image: node
    tty: true
    volumes:
      - "$PWD:/project"
    working_dir: '/project'
    entrypoint: 'bash'  # 'yarn test'
    environment:
      - "APP_URL=${APP_URL}"
      - "SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub"
