name: Ejemplo de Workflow
on: [push, pull_request]

jobs:
  push2main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 1 para la rama main"
  push2dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 2 para la rama dev"
  cratedPR:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1
        run: echo "Este es el trabajo 3 para pull requests a las ramas main o dev"
