name: 01-Demo-github-actions
run-name: ${{ github.actor }} is the user which execute the code
on: [push]
jobs:
  J0101-Exploring-file:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Summary
          Event: ${{ github.event_name }}
          OS: ${{ runner.os }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}"
      - run: echo "${{ github.event_name }} event activated"
      - run: echo "OS ${{ runner.os }}"
      - run: echo "Branch name ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: >
        echo "The ${{ github.repository }} repository
         has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
