---
name: 01-Demo-github-actions
run-name: ${{ github.actor }} is the user which execute the code
# on: [push]
on:
  push:
    branches:
      - "main"
#   schedule:
#     - cron: '* * * * *'

jobs:
  J0101-Exploring-file:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Summary
          Event: ${{ github.event_name }}
          OS: ${{ runner.os }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}"
      - run: |
          echo "Running script"
          echo "my name is tavo"
          cd ${{github.workspace}}
          echo "welcome to tijuana" > foo
          cat foo
          ls
          pwd
          docker --version
          echo "end of file"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: >
          echo "The ${{ github.repository }} repository
          has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: |
          echo "Testing project"
          cd ${{ github.workspace }}/jest-selenium/
          yarn
          cd ${{ github.workspace }}/Docker
          docker compose up -d
          # docker compose exec server sh -c "sudo apt update && sudo apt install -y iproute2 && sudo ss -4tpnl"
          echo "curl server"
          curl "localhost:3000" || echo $?
          echo "curl chrome"
          curl "localhost:4444" || echo $?
          docker compose ps
          docker compose exec tests ls
          docker compose exec tests bash -c "echo 'server'; curl server:3000; echo $?"
          docker compose exec tests bash -c "echo 'chrome'; curl chrome:4444/wd/hub; echo $?"
          docker compose exec tests sh -c "env | sort"
          docker compose exec tests yarn test; echo $?
          docker compose ps
      - run: echo "🍏 This job's status is ${{ job.status }}."
