---
name: 01-Demo-github-actions
run-name: ${{ github.actor }} is the user which execute the code
# on: [push]
on:
  push:
    branches:
      - "main"
#   schedule:
#     - cron: '* * * * *'

jobs:
  J0101-Exploring-file:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Summary
          Event: ${{ github.event_name }}
          OS: ${{ runner.os }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          env-github: ${{ github.FOOBAR }}
          env-env: ${{ env.FOOBAR }}
          alone: ${{ FOOBAR }}
          "
      - run: |
          echo "Running script"
          echo "my name is tavo"
          cd ${{github.workspace}}
          echo "welcome to tijuana" > foo
          cat foo
          ls
          pwd
          docker --version
          echo "end of file"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: >
          echo "The ${{ github.repository }} repository
          has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}


      - name: "Download yarn Dependences with frozen lockfile"
        run: |
          cd ${{ github.workspace }}/jest-selenium/
          yarn --frozen-lockfile
      - name: "Docker compose starts the services"
        run: |
          cd ${{ github.workspace }}/jest-selenium
          docker compose up -d
          echo "waiting for services"
          docker compose exec tests bash -c "echo 'server'; curl -I server:3000 --retry 5 --retry-delay 5 --retry-connrefused; echo $?"
          docker compose exec tests bash -c "echo 'chrome'; curl -I chrome:4444/wd/hub --retry 5 --retry-delay 5 --retry-connrefused; echo $?"
      - run: |
          echo "Yarn test"
          cd ${{ github.workspace }}/jest-selenium
          docker compose exec tests yarn test
      - run: echo "🍏 This job's status is ${{ job.status }}."
