---
name: 02-Selenium-Tests
run-name: ${{ github.actor }} runs a selenium validation

on:
  push:
    branches:
      - "qa/**"

env:
  QA_URL: ${{ secrets.QA_URL }}
  LOCAL_URL: http://server:3000
  APP_URL: ''

defaults:
  run:
    shell: bash
    working-directory: ./jest-selenium

jobs:
  J0201-Selenium:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v3
      - name: Initialize dependences
        run: yarn --frozen-lockfile
      - name: Initialize containers
        run: |
          export APP_URL=${LOCAL_URL}
          echo "QA: ${QA_URL}"
          echo "LOCAL: ${LOCAL_URL}"
          echo "APP: ${APP_URL}"
          echo "-------"
          docker compose up -d
          docker compose exec tests bash -c "echo 'server'; \
            curl \
              -I \
              server:3000 \
              --retry 5 \
              --retry-delay 5 \
              --retry-connrefused; \
            echo $?"
          docker compose exec tests bash -c "echo 'chrome'; \
            curl \
              -I \
              chrome:4444/wd/hub \
              --retry 5 \
              --retry-delay 5 \
              --retry-connrefused; \
            echo $?"
          docker compose logs server
          docker compose logs chrome
      - name: Initialize Tests
        run: docker compose exec tests yarn test
