---
name: 02-Selenium-Tests
run-name: ${{ github.actor }} runs a selenium validation

on:
  push:
    branches:
      - "qa/**"

defaults:
  run:
    shell: bash
    working-directory: ./jest-selenium

jobs:
  J0201-Selenium:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v3
      - name: Setup containers
        run: echo "welcome"
